# Generated by Django 4.1.4 on 2023-04-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctorprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
    ]
