# Generated by Django 4.1.4 on 2023-01-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='purchase_year',
        ),
    ]
